//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.06 at 10:20:35 AM IST 
//


package com.cgi.rabobank.process.statement.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.opencsv.bean.CsvBindByName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="record" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="startBalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="mutation" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="endBalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="reference" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "record"
})
@XmlRootElement(name = "records")
public class Records {

    protected List<Records.Record> record;

    /**
     * Gets the value of the record property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the record property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Records.Record }
     * 
     * 
     */
    public List<Records.Record> getRecord() {
        if (record == null) {
            record = new ArrayList<Records.Record>();
        }
        return this.record;
    }

    /**
     * 
     * @param record
     */
    public void setRecord(List<Records.Record> record) {
        this.record = record;
    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="startBalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="mutation" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="endBalance" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *       &lt;/sequence>
     *       &lt;attribute name="reference" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountNumber",
        "description",
        "startBalance",
        "mutation",
        "endBalance"
    })
    public static class Record {

        @XmlElement(required = true)
        @CsvBindByName(column= "Account Number")
        protected String accountNumber;
        @XmlElement(required = true)
        @CsvBindByName(column = "Description")
        protected String description;
        @CsvBindByName(column = "Start Balance")
        protected float startBalance;
        @CsvBindByName(column = "Mutation")
        protected float mutation;
        @CsvBindByName(column = "End Balance")
        protected float endBalance;
        @XmlAttribute(name = "reference")
        @CsvBindByName(column = "Reference")
        protected Integer reference;

        /**
         * Gets the value of the accountNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountNumber() {
            return accountNumber;
        }

        /**
         * Sets the value of the accountNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public Record setAccountNumber(String value) {
            this.accountNumber = value;
            return this;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public Record setDescription(String value) {
            this.description = value;
            return this;
        }

        /**
         * Gets the value of the startBalance property.
         * 
         */
        public float getStartBalance() {
            return startBalance;
        }

        /**
         * Sets the value of the startBalance property.
         * 
         */
        public Record setStartBalance(float value) {
            this.startBalance = value;
            return this;
        }

        /**
         * Gets the value of the mutation property.
         * 
         */
        public float getMutation() {
            return mutation;
        }

        /**
         * Sets the value of the mutation property.
         * 
         */
        public Record setMutation(float value) {
            this.mutation = value;
            return this;
        }

        /**
         * Gets the value of the endBalance property.
         * 
         */
        public float getEndBalance() {
            return endBalance;
        }

        /**
         * Sets the value of the endBalance property.
         * 
         */
        public Record setEndBalance(float value) {
            this.endBalance = value;
            return this;
        }

        /**
         * Gets the value of the reference property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getReference() {
            return reference;
        }

        /**
         * Sets the value of the reference property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public Record setReference(Integer value) {
            this.reference = value;
            return this;
        }

    }

}
